### ISSUE TITLE
max short description length/header count off by one

### ISSUE THREAD

**Issue by charharharhar** [jimmy-guzman/gitzy#53]
- `gitzy` version: 1.3.1
- `node` version: 12.12.0
- `commitlint` version: 11.0.0

<img width="802" alt="Screen Shot 2021-02-19 at 11 49 25 AM" src="https://user-images.githubusercontent.com/13672817/108542012-c891c280-72a8-11eb-9158-df7d7d638bd4.png">

### What you did:
- made a short description of max length (64)
### What happened:
```header must not be longer than 64 characters, current length is 65```
### Reproduction:
make a commit with the max description length (64/64)

### Problem description:
possibly the emoji is accounted for in description length?
### Suggested solution:
updating max length

**Comment by jimmy-guzman** [comment]
@charharharhar good catch! I forgot to account for [this space](https://github.com/jimmy-guzman/gitzy/blob/master/src/utils/format-message/formatGitMessage.ts#L49) when determining wether or not it's past the max length
